import * as React from 'react';
import Head from 'next/head';
import CssBaseline from '@mui/material/CssBaseline';
import Container from '@mui/material/Container';
import Paper from '@mui/material/Paper';
import Box from '@mui/material/Box';
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import MenuIcon from '@mui/icons-material/Menu';

export interface ILayoutProps {
    children: any
}

export default function Layout (props: ILayoutProps) {
  return (
    <Box>
        <Head>
        <title>Crowdfund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
            <React.Fragment>
                <CssBaseline />
                <Container>
                    <Paper elevation={3}>
                        <Box sx={{ flexGrow: 1 }}>
                            <AppBar position="static">
                                <Toolbar>
                                <IconButton
                                    size="large"
                                    edge="start"
                                    color="inherit"
                                    aria-label="menu"
                                    sx={{ mr: 2 }}
                                >
                                    <MenuIcon />
                                </IconButton>
                                <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                                    Crowdfund
                                </Typography>
                                <Button color="inherit">Login</Button>
                                </Toolbar>
                            </AppBar>
                        </Box>
                        <Box sx={{ p: 4 }}>
                        { props.children }
                        </Box>
                    </Paper>
                </Container>
            </React.Fragment>
        </main>
    </Box>
  );
}


  
